AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for running Kittens Carousel Static Website on EC2.
  It uses Amazon Linux 2 (compatible with t2.micro Free Tier) and deploys the website from a public GitHub repository.

Parameters:
  keypair:
    Description: Choose your keypair
    Type: AWS::EC2::KeyPair::KeyName
    Default: first_key

  ParameterName:
    Description: Choose your imageid (Amazon Linux 2)
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  mySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows ssh and http
      GroupName: okt-sec-grp-aws20tr
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

  mywebserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ParameterName
      InstanceType: t2.micro
      KeyName: !Ref keypair
      SecurityGroupIds:
        - !Ref mySecGrp
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install -y httpd wget
        FOLDER="https://raw.githubusercontent.com/macdevopss/aws-projects/main/101-kittens-carousel-static-website-ec2/static-web"
        cd /var/www/html/
        wget ${FOLDER}/index.html
        wget ${FOLDER}/cat0.jpg
        wget ${FOLDER}/cat1.jpg
        wget ${FOLDER}/cat2.jpg
        systemctl start httpd
        systemctl enable httpd

Outputs:
  WebSiteURL:
    Description: URL of website
    Value: !Sub 
      - "http://${PublicDNS}"
      - PublicDNS: !GetAtt mywebserver.PublicDnsName
